[functions]

[functions.stripe-webhook]
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[auth.email.template.confirmation]
subject = "Confirm your signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset your password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your magic link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm email change"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.reauthentication]
subject = "Confirm reauthentication"
content_path = "./supabase/templates/reauthentication.html"

[auth.email.template.invite]
subject = "You're invited"
content_path = "./supabase/templates/invite.html"
